
export const SET_SEARCH_INGREDIENTS = 'SET_SEARCH_INGREDIENTS';
export const SET_SEARCH_INGREDIENTS_FAILED = 'SET_SEARCH_INGREDIENTS_FAILED';

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';

export const FETCH_INGREDIENT_DETAILS = 'FETCH_ING_DETAILS';
export const FETCH_INGREDIENT_DETAILS_FAILED = 'FETCH_ING_DETAILS_FAILED';

export const FETCH_RECIPES_GIVEN_INGS='FETCH_RECIPES_GIVEN_INGS';
